### ISSUE TITLE
[Perlin] Бикубическая интерполяция

### ISSUE THREAD

**Issue by pavel-b-novikov** [Draxzor/nsudotnet#2]
Не вижу кода для бикубической интерполяции, с помощью которой и делаются шумы Перлина.

**Comment by Draxzor** [comment]
Пофиксил.

**Comment by pavel-b-novikov** [comment]
Чет белый шум какой-то выдает. Откалибруйте пожалуйста

**Comment by pavel-b-novikov** [comment]
Я откопал свою реализацию этого алгоритма. Получаться должно что-то вроде такого 
![image](https://user-images.githubusercontent.com/2521412/40616584-cf74404c-62b5-11e8-93e1-c4f0cd023f14.png)

![image](https://user-images.githubusercontent.com/2521412/40616632-fb844240-62b5-11e8-9b6f-0a1209d1c3cb.png)

В зависимости от настроек

**Comment by pavel-b-novikov** [comment]
Слушайте, а вы вообще делаете цветной генератор или черно-белый?

**Comment by Draxzor** [comment]
Цветной, если приблизить, то видно что он цветной. Сейчас попробую привести к виду, как на картинке.

**Comment by pavel-b-novikov** [comment]
Да нет. Для цветного нужно ажно 9 сеток, а у вас только 3.
Вот что мне выдает ваша программа: 
![image](https://user-images.githubusercontent.com/2521412/40624272-ce13cc34-62d5-11e8-8df0-3d2a2b3ea70c.png)

**Comment by Draxzor** [comment]
Странно, потому что у меня вот это

![default](https://user-images.githubusercontent.com/21261136/40624809-ed6ce39c-62d8-11e8-81fe-39f013729313.PNG)

Я как раз и использую 9 сеток, по 3 на каждый цвет, как в ТЗ написано

**Comment by pavel-b-novikov** [comment]
В любом случае картинка далека от того, что должно быть. Сейчас это просто шум

**Comment by Draxzor** [comment]
Пофиксил. Оказывается просто передавал не те параметры в метод интерполяции, потерял уйму времени, думая, что не так.
Теперь картинка похожа на то, что вы постили.
![noise](https://user-images.githubusercontent.com/21261136/40625781-9cd966ac-62de-11e8-9692-38f93a2f4046.png)
